pool:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  displayName: 'Use Node version'
  inputs:
    versionSpec: 12.x

- script: |
    npm test
    npm run build
    npm test
  displayName: 'npm install and build'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/junit.xml'